### ISSUE TITLE
Is this for channels queue? Does it work?

### ISSUE THREAD

**Issue by killereturns** [Cerberus-ik/queue-bot#1]
Hi, im not sure if this is for channels or music... not sure... if its for channels.. does it work propertly? thanks!

PS: i ask here cause i didnt find another place

**Comment by Cerberus-ik** [comment]
The bot was created for one very specific discord guild. It does not have any music functionallity and I am not really sure if you misunderstood the bot.

**Comment by killereturns** [comment]
Seems that... but... what does it do then? Sorry about my english man :D

**Comment by Cerberus-ik** [comment]
You can/could use the bot to automate a custom queue on one discord server.
